from enum import Enum


class StoreType(str, Enum):
    CAR_DEALER = "car_dealer"
    GAS_STATION = "gas_station"
    ART_GALLERY = "art_gallery"
    LIBRARY = "library"
    WINE_BAR = "wine_bar"
    DRUGSTORE = "drugstore"
    PHARMACY = "pharmacy"
    FLORIST = "florist"
    STORAGE = "storage"
    TAILOR = "tailor"
    TOUR_AGENCY = "tour_agency"
    TOURIST_INFORMATION_CENTER = "tourist_information_center"
    TRAVEL_AGENCY = "travel_agency"
    BICYCLE_STORE = "bicycle_store"
    BOOK_STORE = "book_store"
    CLOTHING_STORE = "clothing_store"
    CONVENIENCE_STORE = "convenience_store"
    DEPARTMENT_STORE = "department_store"
    ELECTRONICS_STORE = "electronics_store"
    FURNITURE_STORE = "furniture_store"
    GREENGROCER = "grocery_or_supermarket"
    HARDWARE_STORE = "hardware_store"
    HOME_GOODS_STORE = "home_goods_store"
    JEWELRY_STORE = "jewelry_store"
    LIQUOR_STORE = "liquor_store"
    PET_STORE = "pet_store"
    SHOE_STORE = "shoe_store"
    SHOPPING_MALL = "shopping_mall"
    SPORTING_GOODS_STORE = "sporting_goods_store"
    GENERAL_STORE = "store"
    SUPERMARKET = "supermarket"
